### PR TITLE
Add PL2303G driver

### PR DESCRIPTION
**Pull request by Plastix**
**Background:**
Recently, a new chip revision of the PL2303 USB-to-serial converter, PL2303HXN, appeared on the market. This family includes 6 variants, PL2303GC (0x23a3), PL2303GB (0x23b3), PL2303GT (0x23c3), PL2303GL (0x23d3), PL2303GE (0x23e3), and PL2303GS (0x23f3).

This commit adds support for the PL2303GC (0x23a3).

**Modifications**:
* Add a new `PL2303GSerialDevice` driver. It is based off of the existing `PL2303SerialDevice` driver.
* Add `PL2303GIds` whielist for the new variants. This allows us to identify the new variants separately and not break the older driver.
* Update `UsbSerialDevice` to identify PL2303G variants and use the new `PL2303GSerialDevice` driver.

### CODE REVIEW

**Comment by zer0page** [comment]
nice find! when forking the driver, are there any changes other than adding the new device type?

**Comment by zer0page** [comment]
@squareup/aperipherals

**Review by zer0page — APPROVED** [review]

**Comment by Plastix** [comment]
@zer0page There are essentially just different control codes constants

**Comment by Plastix** [comment]
We're treating this as a different driver/variant so we can avoid touching the old one and breaking it.

**Comment by Plastix** [comment]
FYI this code does not follow Android Register standards. I followed the library style guide

**Pull request merged**
